In [1]:
import numpy as np

# 1. Calculate eigenvalues and eigenvectors from the covariance matrix

## 1.1. Different result (between np.linalg.eig and np.linalg.eigh) if the matrix is not symmetrcic

In [2]:
A = np.array([[1, 2], [3, 4]])

In [3]:
eigenvalues, eigenvectors = np.linalg.eig(A)  # general case
eigenvalues, eigenvectors

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [4]:
(eigenvectors[:, 0]**2).sum()  # check if the eigenvector is normalized

1.0000000000000002

In [5]:
(eigenvectors[:, 1]**2).sum()  # check if the eigenvector is normalized

1.0

In [6]:
eigenvalues, eigenvectors = np.linalg.eigh(A)  # symmetric case
eigenvalues, eigenvectors

(array([-0.85410197,  5.85410197]),
 array([[-0.85065081,  0.52573111],
        [ 0.52573111,  0.85065081]]))

In [7]:
(eigenvectors[:, 0]**2).sum()  # check if the eigenvector is normalized

0.9999999999999998

In [8]:
(eigenvectors[:, 1]**2).sum()  # check if the eigenvector is normalized

0.9999999999999998

## 1.2. Still different resulf if the matrix is symmetric

In [9]:
A = np.array([[1, 2], [2, 4]])

In [10]:
eigenvalues, eigenvectors = np.linalg.eig(A) # general case
eigenvalues, eigenvectors

(array([0., 5.]),
 array([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]]))

In [11]:
(eigenvectors[:, 0]**2).sum()  # check if the eigenvector is normalized

0.9999999999999999

In [12]:
(eigenvectors[:, 1]**2).sum()  # check if the eigenvector is normalized

0.9999999999999999

In [13]:
eigenvalues, eigenvectors = np.linalg.eigh(A)  # symmetric case
eigenvalues, eigenvectors

(array([0., 5.]),
 array([[-0.89442719,  0.4472136 ],
        [ 0.4472136 ,  0.89442719]]))

In [14]:
(eigenvectors[:, 0]**2).sum()  # check if the eigenvector is normalized

0.9999999999999999

In [15]:
(eigenvectors[:, 1]**2).sum()  # check if the eigenvector is normalized

0.9999999999999999

# 2. Double check by calculating back the covariance matrix

## 2.1. Not symmetric

In [16]:
A = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)  # general case
eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)

array([[1., 2.],
       [3., 4.]])

In [17]:
A = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eigh(A)  # wrong result
eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)

array([[1., 3.],
       [3., 4.]])

## 2.2. Symmetric

In [18]:
A = np.array([[1, 2], [2, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)  # general case
eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)

array([[1., 2.],
       [2., 4.]])

In [19]:
A = np.array([[1, 2], [2, 4]])
eigenvalues, eigenvectors = np.linalg.eigh(A)  # general case
eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)

array([[1., 2.],
       [2., 4.]])

## 2.3. Check scalling

In [22]:
A = np.array([[1, 2], [2, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)  # general case

a = 3
b = 5
print(eigenvectors)
eigenvectors[:, 0] *= a
eigenvectors[:, 1] *= b
print(eigenvectors)
eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)

[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]
[[-2.68328157 -2.23606798]
 [ 1.34164079 -4.47213595]]


array([[1., 2.],
       [2., 4.]])

In [23]:
A = np.array([[1, 2], [2, 4]])
eigenvalues, eigenvectors = np.linalg.eigh(A)  # symetric case

a = 3
b = 10
print(eigenvectors)
eigenvectors[:, 0] *= a
eigenvectors[:, 1] *= b
print(eigenvectors)
eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)

[[-0.89442719  0.4472136 ]
 [ 0.4472136   0.89442719]]
[[-2.68328157  4.47213595]
 [ 1.34164079  8.94427191]]


array([[1., 2.],
       [2., 4.]])

# 3. Conclusion

- Given a covariance matrix (of a 2D Gaussian distribution), the corresponding eigenvectors are NOT unique.  For example, if $\mathbf{v}$ is an eigenvector, then $c\mathbf{v}$ (where $c$ is any non-zero scalar) is also an eigenvector corresponding to the same eigenvalue.

- Given a covariance matrix (of a 2D Gaussian distribution), the corresponding eigenvalues are unique.

- If the matrix is covariance matrix (symmetric), we can use both np.linalg.eig or np.linalg.eigh (though different eigenvetors, they are just the reverse direction).

- Indeed, the scalar multiples of the 2 eigenvectors do not matter when recalculating back the covariance matrix (2 different scalars on 2 eigenvectors do not matter)