In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
from dasly.utils import *

In [3]:
# Test example
lines1 = np.array([
    [1, pd.Timestamp('2023-12-31 22:44:59'), 11, pd.Timestamp('2023-12-31 22:45:00')],
    [13, pd.Timestamp('2023-12-31 22:40:00'), 16, pd.Timestamp('2023-12-31 22:42:00')],
    [3, pd.Timestamp('2023-12-31 22:44:00'), 3, pd.Timestamp('2023-12-31 22:45:00')],
    [1, pd.Timestamp('2023-12-31 22:44:00'), 3, pd.Timestamp('2023-12-31 22:45:00')]
])

lines2 = np.array([
    [1, pd.Timestamp('2023-12-31 22:40:00'), 20, pd.Timestamp('2023-12-31 22:45:00')],
    [3, pd.Timestamp('2023-12-31 22:45:00'), 6, pd.Timestamp('2023-12-31 22:42:00')],
    [10, pd.Timestamp('2023-12-31 22:44:00'), 30, pd.Timestamp('2023-12-31 22:41:00')],
    [4, pd.Timestamp('2023-12-31 22:41:00'), 13, pd.Timestamp('2023-12-31 22:45:00')]
])

lines3 = np.array([
    [3, datetime(2023, 12, 31, 22, 45, 0), 1, datetime(2023, 12, 31, 22, 44, 0)],
    [1, datetime(2023, 12, 31, 22, 44, 0), 3, datetime(2023, 12, 31, 22, 45, 0)],
    [3, datetime(2023, 12, 31, 22, 44, 0), 1, datetime(2023, 12, 31, 22, 44, 0)],
    [1, datetime(2023, 12, 31, 22, 44, 0), 3, datetime(2023, 12, 31, 22, 44, 0)]
])

lines4 = np.array([
    [6, 2, 6, 4],
    [5, 6, 9, 8],
    [6, 10, 20, 10],
    [7, 10, 7, 10]
])

lines5 = np.floor(np.array([
    # [1.3, 2.5, 5.3, 2.1],
    [3.3, 6.1, 3.4, 8.7],
    [9.4, 10.4, 11.6, 12.5],
    [13.3, 14.3, 15.3, 16.5]
])).astype(float)


# lines5 = np.array([
#     [6, 2, 6, 4],
#     [5, 6, 9, 8],
#     [6, 10, 20, 10],
#     [7, 10, 7, 10]
# ]).astype(float)

In [8]:
calculate_line_gap(lines1, np.array([]))

IndexError: tuple index out of range

In [9]:
import numpy as np

# Create a 4x3 array of random floats
random_floats = np.random.random((4, 3))

# Introduce some inf and nan values
random_floats[0, 0] = np.inf   # Set one element to infinity
random_floats[1, 1] = -np.inf  # Set one element to negative infinity
random_floats[2, 2] = np.nan   # Set one element to NaN
random_floats

array([[       inf, 0.81213601, 0.00895534],
       [0.67197529,       -inf, 0.06570769],
       [0.9702405 , 0.9613724 ,        nan],
       [0.05827237, 0.50041831, 0.01480279]])

In [11]:
# Find the indices of the minimum distances
min_indices = np.nanargmin(random_floats, axis=0)
min_indices

array([3, 1, 0])

In [13]:
# Find the minimum distances for each point in b
min_distances = np.nanmin(random_floats, axis=0)
min_distances

array([0.05827237,       -inf, 0.00895534])

In [6]:
a = np.array([[11, 12, 10, 12], [10, 11, 11, 11]])
calculate_speed(a), calculate_slope(a)

(array([-inf,  inf]), array([-0.,  0.]))

In [8]:
calculate_slope(a) < 0

array([False, False])

In [17]:
calculate_slope()

inf

In [7]:
0/0

ZeroDivisionError: division by zero

In [5]:
np.argmin(random_floats, axis=0)

array([3, 1, 2])

In [7]:
# Find the indices of the minimum distances
min_indices = np.argmin(random_floats, axis=0)
# Find the minimum distances for each point in b
min_distances = np.min(random_floats, axis=0)
# Create a mask for distances below the threshold
mask = min_distances < threshold
# Create an array to hold the new names
lines_id_reassigned = np.where(
    mask, previous_lines_id[min_indices], lines_id)
return lines_id_reassigned

inf

In [5]:
for num_i, i in enumerate(lines1):
    for num_j, j in enumerate(lines3):
        print(num_i, num_j)
        print(result[num_i, num_j])
        validate = gap_line(i, j)
        print(validate)
        print()

0 0
78.0


TypeError: float() argument must be a string or a number, not 'Timestamp'

In [13]:
for num_i, i in enumerate(lines4):
    print(num_i)

0
1
2
3
