In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
from dasly.utils import *

In [2]:
import numpy as np

def test_intersect_space():
    # Case 1: Both line1 and line2 are 1D arrays (shape (4,))
    line1_1d = np.array([0, 0, 10, 10])
    line2_1d = np.array([5, 5, 15, 15])
    result_1d = intersect_space(line1_1d, line2_1d)
    expected_1d = np.array([5, 10])
    assert np.array_equal(result_1d, expected_1d), f"1D Case Failed: {result_1d}"

    # Case 2: line1 is 2D with shape (N=2, 4), line2 is 1D with shape (4,)
    line1_2d = np.array([[0, 0, 10, 10], [5, 5, 15, 15]])
    line2_1d = np.array([5, 5, 12, 12])
    result_2d_1d = intersect_space(line1_2d, line2_1d)
    expected_2d_1d = np.array([[5, 10], [5, 12]])[:, np.newaxis, :]
    assert np.array_equal(result_2d_1d, expected_2d_1d), f"2D-1D Case Failed: {result_2d_1d}"

    # Case 3: line1 is 1D with shape (4,), line2 is 2D with shape (M=2, 4)
    line1_1d = np.array([5, 5, 12, 12])
    line2_2d = np.array([[0, 0, 10, 10], [6, 6, 14, 14]])
    result_1d_2d = intersect_space(line1_1d, line2_2d)
    expected_1d_2d = np.array([[5, 10], [6, 12]])[np.newaxis, :, :]
    assert np.array_equal(result_1d_2d, expected_1d_2d), f"1D-2D Case Failed: {result_1d_2d}"

    # Case 4: Both line1 and line2 are 2D arrays (shape (N=2, 4) and (M=2, 4))
    line1_2d = np.array([[0, 0, 10, 10], [5, 5, 15, 15]])
    line2_2d = np.array([[5, 5, 12, 12], [6, 6, 14, 14]])
    result_2d_2d = intersect_space(line1_2d, line2_2d)
    expected_2d_2d = np.array([[[5, 10], [6, 10]], 
                               [[5, 12], [6, 14]]])
    assert np.array_equal(result_2d_2d, expected_2d_2d), f"2D-2D Case Failed: {result_2d_2d}"

    print("All test cases passed!")

# Run the test function
test_intersect_space()

All test cases passed!


In [3]:
# Test example
lines1 = np.array([
    # [1, pd.Timestamp('2023-12-31 22:43:00'), 11, pd.Timestamp('2023-12-31 22:45:00')],
    [13, pd.Timestamp('2023-12-31 22:40:00'), 16, pd.Timestamp('2023-12-31 22:42:00')],
    [3, pd.Timestamp('2023-12-31 22:44:00'), 3, pd.Timestamp('2023-12-31 22:45:00')],
    [1, pd.Timestamp('2023-12-31 22:44:00'), 3, pd.Timestamp('2023-12-31 22:45:00')]
], dtype=object)

lines2 = np.array([
    [1, pd.Timestamp('2023-12-31 22:40:00'), 20, pd.Timestamp('2023-12-31 22:45:00')],
    [3, pd.Timestamp('2023-12-31 22:45:00'), 6, pd.Timestamp('2023-12-31 22:42:00')],
    [10, pd.Timestamp('2023-12-31 22:44:00'), 30, pd.Timestamp('2023-12-31 22:41:00')],
    [4, pd.Timestamp('2023-12-31 22:41:00'), 13, pd.Timestamp('2023-12-31 22:45:00')]
], dtype=object)



# lines = np.array([
#     [3, datetime(2023, 12, 31, 22, 45, 0), 1, datetime(2023, 12, 31, 22, 44, 0)],
#     [1, datetime(2023, 12, 31, 22, 44, 0), 3, datetime(2023, 12, 31, 22, 45, 0)],
#     [3, datetime(2023, 12, 31, 22, 44, 0), 1, datetime(2023, 12, 31, 22, 44, 0)],
#     [1, datetime(2023, 12, 31, 22, 44, 0), 3, datetime(2023, 12, 31, 22, 44, 0)]
# ], dtype=object)

In [4]:
# Ensure lines1 and lines2 are at least 2D (shape (N, 4) and (M, 4))
lines1 = np.atleast_2d(lines1)
lines2 = np.atleast_2d(lines2)

# Calculate the space intersection limits for each pair of lines
space_intersection = intersect_space(lines1, lines2)

# if len(space_intersection) == 0:
#     return np.full((lines1.shape[0], lines2.shape[0]), np.inf)

# Calculate the slope for each line segment
slope1 = calculate_slope(lines1)[:, np.newaxis]  # Shape (N, 1)
# slope2 = calculate_slope(lines2)[np.newaxis, :]  # Shape (1, M)

# # Extract the start points and times
# s11, t11 = lines1[:, 0][:, np.newaxis], lines1[:, 1][:, np.newaxis]
# s21, t21 = lines2[:, 0][np.newaxis, :], lines2[:, 1][np.newaxis, :]

In [5]:
speed = np.array([0, 1, 2, 3, 4])

with np.errstate(divide='ignore', invalid='ignore'):
    slope = np.where(speed == 0, np.inf, 1 / speed)

In [7]:
calculate_slope(lines1)

array([40., inf, 30.])

In [11]:
calculate_speed(lines1).astype(float)

array([0.025     , 0.        , 0.03333333])

In [19]:
space_intersection

array([[[13, 16],
        [13, 6],
        [13, 16],
        [13, 13]],

       [[3, 3],
        [3, 3],
        [10, 3],
        [4, 3]],

       [[1, 3],
        [3, 3],
        [10, 3],
        [4, 3]]], dtype=object)

In [45]:
lines1 = lines[0]
lines2 = lines[1]

In [48]:
space_intersection = intersect_space(lines1, lines2)
space_intersection

array([13, 11], dtype=object)

In [52]:
 np.atleast_2d(np.array([1,2,3,4]))

array([[1, 2, 3, 4]])

In [46]:
calculate_distance(lines1, lines2)

352.0

In [2]:
import numpy as np
import pandas as pd
from datetime import datetime

# Single line segment for both lines1 and lines2
line1_1d = np.array([0, pd.Timestamp('2023-01-01 00:00:00'), 10, pd.Timestamp('2023-01-01 00:00:10')])
line2_1d = np.array([5, pd.Timestamp('2023-01-01 00:00:05'), 15, pd.Timestamp('2023-01-01 00:00:15')])

result_1d = calculate_distance(line1_1d, line2_1d)
print(f"Test Case 1: {result_1d}")
# Expected Output: 0.0 (both lines have the same speed and intersect perfectly)

TypeError: arg must be a string, timedelta, list, tuple, 1-d array, or Series